### ISSUE TITLE
Added New Question on Arrays

### ISSUE THREAD

**Issue by AnkitMajee** [AnkitMajee/DataStructureInCpp#10]
Any New question or question you got in you OA and interviews (if any).

**Comment by codebydeep** [comment]
Heyy @AnkitMajee Could you assign this issue to me?

**Comment by AnkitMajee** [comment]
Go Ahead @codebydeep

**Comment by codebydeep** [comment]
Heyy @AnkitMajee I have made the necessary changes to the project by Adding Array Questions. Please check it out & Kindly merge my Pull Request. Thanks!

**Comment by AnkitMajee** [comment]
Merge
