### ISSUE TITLE
Distinct Subsequences

### ISSUE THREAD

**Issue by AnujKshatriya** [AnkitMajee/DataStructureInCpp#102]
Hey @AnkitMajee I would like to add Distinct Subsequence question on topic - DP with strings, it is marked as hard question on leetcode .
I would like to add the cpp code of it, in you DP folder, under hacktoberfest-2024.
Please assign this issue to me.

**Comment by AnkitMajee** [comment]
Go ahead and raise your PR

**Comment by AnujKshatriya** [comment]
I have raised a pr, please check it

**Comment by AnkitMajee** [comment]
Merged! Thanks for such a good dp question feels free to add more into it

**Comment by AnujKshatriya** [comment]
Welcome, For sure.
