### ISSUE TITLE
infix to prefix using stack

### ISSUE THREAD

**Issue by laiba-Ashfaq** [AnkitMajee/DataStructureInCpp#109]
i would like to to convert infix expression to prefix using stack concept in c++ please assign to it to me under hacktoberfest 2024

**Comment by laiba-Ashfaq** [comment]
i send pull request plz check it and add merge it with label of hacktoberfest 2024

**Comment by AnkitMajee** [comment]
Yeah I have merged! 
looking for more such PRs
