### ISSUE TITLE
Added new question on Binary Search

### ISSUE THREAD

**Issue by AnkitMajee** [AnkitMajee/DataStructureInCpp#13]
Any New question or question you got in you OA and interviews (if any).

**Comment by Sanskar0820** [comment]
Hey @AnkitMajee I want to work on this issue through hacktoberfest2024.

**Comment by AnkitMajee** [comment]
@Sanskar0820 
Go Ahead Assigned

**Comment by ALANT535** [comment]
Hey @AnkitMajee I would also like to contribute more questions to this. I have already raised a PR for 2 BS questions. Would like to work on this through hacktoberfest2024 as well.
Thanks!

**Comment by AnkitMajee** [comment]
@ALANT535 Yes Go Ahead PR something new thats not in the Binary Search topic

Yes once you do that I'll merge it under hactoberfest2024
