### ISSUE TITLE
Added new question on Sorting

### ISSUE THREAD

**Issue by AnkitMajee** [AnkitMajee/DataStructureInCpp#14]
Any New question or question you got in you OA and interviews (if any).

**Comment by codebydeep** [comment]
@AnkitMajee  Please assign this to me. I can work on it.

**Comment by codebydeep** [comment]
Heyy @AnkitMajee I have made a Pull Request after completing all the changes. Please merge it.

**Comment by AnkitMajee** [comment]
merged
