### ISSUE TITLE
add deque in cpp

### ISSUE THREAD

**Issue by Ankitmohanty2** [AnkitMajee/DataStructureInCpp#25]
i want to work on this issue through ahcktoberfest2024

**Comment by AnkitMajee** [comment]
@Ankitmohanty2 Go Ahead!
Assigned

**Comment by Ankitmohanty2** [comment]
thank you

**Comment by AnkitMajee** [comment]
@Ankitmohanty2 
Do give a Star if this repository helps you in future.
Also this would keep me motivated to maintain for all Problem solving lovers.
