### ISSUE TITLE
Add Contributors name in Readme file

### ISSUE THREAD

**Issue by neyhere07** [AnkitMajee/DataStructureInCpp#39]
I'd like to suggest for adding all the Contributors name to the project's README. This would be a great way to acknowledge and thank everyone who has contributed to the project so far. Recognizing contributors can help build a stronger community and encourage more people to contribute.

## Demo : 

https://github.com/user-attachments/assets/13a0d572-3639-4441-9b47-27efff71f656

<hr><br>
If you like this idea, I would like to work on this issue. Kindly assign me under Hacktoberfest 2024. Thank you!
@AnkitMajee

**Comment by AnkitMajee** [comment]
That's true 💯 @neyhere07 I was also thinking to do that glad you made the change 

Great addition! Your changes make things so much better!
please make this RP

**Comment by neyhere07** [comment]
Sure! I'm working now!

**Comment by neyhere07** [comment]
Raised the PR! Please review!

**Comment by AnkitMajee** [comment]
Great
