### ISSUE TITLE
Binary Search Tree implementation is missing in tree section

### ISSUE THREAD

**Issue by dkumar1304** [AnkitMajee/DataStructureInCpp#45]
I want to add Binary Search Tree Implementation for the Trees section(S).

**Comment by dkumar1304** [comment]
Please assign this issue to me

**Comment by dkumar1304** [comment]
Sorry this is my first time Please assign me this issue

**Comment by AnkitMajee** [comment]
No worries you Got your 1st github Badge Congrats🎉

Assigned

**Comment by dkumar1304** [comment]
Thank you so much.
