### ISSUE TITLE
Add ZigZag Tree Traversal in tree section

### ISSUE THREAD

**Issue by dkumar1304** [AnkitMajee/DataStructureInCpp#53]
Input:
        1
      /   \
     2    3
    / \    /   \
   4   5 6   7
Output:
1 3 2 4 5 6 7
Explanation:
For level 1 going left to right, we get traversal as {1}.
For level 2 going right to left, we get traversal as {3,2}.
For level 3 going left to right, we get traversal as {4,5,6,7}.
Merging all this traversals in single array we get {1,3,2,4,5,6,7}

I want add zig-zag Traversal.
Please assign this issue to me.

**Comment by dkumar1304** [comment]
Please assign this issue to me.

**Comment by AnkitMajee** [comment]
Assigned
