### ISSUE TITLE
Problem: Find Largest Rectangle in Histogram  (DSA in C++)

### ISSUE THREAD

**Issue by Nikhil-gi** [AnkitMajee/DataStructureInCpp#62]
Request to Assign: Find Largest Rectangle in Histogram (DSA in C++)
Hello @AnkitMajee  ,

I would like to work on the "Find Largest Rectangle in Histogram" problem as part of Hacktoberfest and Hacktoberfest2024. Could you please assign this issue to me?
I will implement an efficient solution in C++ using stacks, ensuring the time complexity is O(n). I’ll also provide detailed comments, explanations, and cover various edge cases in the test cases.

Looking forward to your confirmation!

Thanks,
Nikhil

**Comment by AnkitMajee** [comment]
Sure go ahead @Nikhil-gi
