### ISSUE TITLE
Set Matrix Zero Problem

### ISSUE THREAD

**Issue by NinadShegokar** [AnkitMajee/DataStructureInCpp#73]
Hello @AnkitMajee, 

I would like to add the Set Matrix Zero Problem to "F) Array/2D array". It is a classic 2D-array problem and would make a helpful addition to the repository. Can you please assign it to me for my contribution to Hacktoberfest24.

I will make sure to program the most efficient solution along with test cases and their outputs. The code will also include user input and output result display.

**Comment by AnkitMajee** [comment]
Hi @NinadShegokar 
Go ahead Assigned!
