### ISSUE TITLE
To add "Best Time to Buy and Sell Stock II" Problem 

### ISSUE THREAD

**Issue by anmol-tripathi83** [AnkitMajee/DataStructureInCpp#76]
Hello @AnkitMajee 
As a newbie and want to contribute in your Repository
I want to add "Best Time to Buy and Sell stock II" leetcode problem number 122
kindly assign this task under hacktober fest 2024

Problem statement: You are given an integer array prices where prices[i] is the price of a given stock on the i th day.
On each day, you may decide to buy and/or sell the stock. You can only hold at most one share of the stock at any time. However, you can buy it then immediately sell it on the same day.
Find and return the maximum profit you can achieve.

Sample TestCase:
Input: prices = [7,1,5,3,6,4]
Output: 7
Buy on day 2 (price = 1) and sell on day 3 (price = 5), profit = 5-1 = 4
Then buy on day 4 (price = 3) and sell on day 5 (price = 6), profit = 6-3 = 3
Total profit is 4 + 3 = 7

**Comment by AnkitMajee** [comment]
Go Ahead
