### ISSUE TITLE
N Queen Problem using Backtracking

### ISSUE THREAD

**Issue by AnujKshatriya** [AnkitMajee/DataStructureInCpp#77]
Hello @AnkitMajee 

I would like to add the N Queen Problem using Backtracking. It is fundamental yet most important question of backtracking from interview perspective. Can you please assign it to me for my contribution to Hacktoberfest24.

I will make sure to program the most efficient solution along with test cases and their outputs.

**Comment by AnkitMajee** [comment]
Go ahead
