### ISSUE TITLE
Valid Palindrome Problem

### ISSUE THREAD

**Issue by NinadShegokar** [AnkitMajee/DataStructureInCpp#84]
Hello @AnkitMajee,

I would like to add the Valid Palindrome Problem under "I) String"

Description: A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers.

**Comment by AnkitMajee** [comment]
Assigned
