### ISSUE TITLE
Add : "Critical Connection in Network" Problem

### ISSUE THREAD

**Issue by AnujKshatriya** [AnkitMajee/DataStructureInCpp#89]
#### Problem Summary:
- **Problem Statement**:  
 There are `n` servers numbered from `0` to `n - 1`, connected by undirected server-to-server connections. Each connection is represented by `connections[i] = [ai, bi]`, indicating a connection between servers `ai` and `bi`. Every server can reach other servers either directly or indirectly through the network.
  
  A **critical connection** is defined as a connection that, if removed, will cause some servers to become unreachable from others. The task is to find and return all such critical connections in any order.

#### Why This Problem?
This problem is a great addition to DSA practice for the following reasons:
- It involves graph theory concepts, specifically **bridges** in a graph, which are useful in understanding critical points in a network.
- It provides practice in applying **DFS (Depth-First Search)** algorithms and **Tarjan's algorithm** for bridge-finding.
- It is an interesting and practical problem related to real-world scenarios like network resilience and reliability.

Can you please assign it to me for my contribution to Hacktoberfest24.

**Comment by AnkitMajee** [comment]
Assigned!
