### ISSUE TITLE
Infix to Postfix solution

### ISSUE THREAD

**Issue by anaghapuv** [AnkitMajee/DataStructureInCpp#90]
Hey @AnkitMajee,
I would like to add the cpp code to convert an infix expression to a postfix expression, in you stack folder, under hacktoberfest-2024.
Please assign this issue to me.

**Comment by AnkitMajee** [comment]
Assigned!

**Comment by itsharshpro** [comment]
[#98](https://github.com/AnkitMajee/DataStructureInCpp/pull/98) solved it
